[package]
name = "clean_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
iai = "0.1"
criterion = "0.3.6"
rand = "0.8.5"

[[bench]]
name = "vtbl_bench"
harness = false
html_reports = true
